sudo: required 

services:
        -docker

before_install:
        - docker build -t tkavuri/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tkavuri/multi-docker npm test


after_success:
        - docker build -t tkavuri/multi-client ./client
        - docker build -t tkavuri/multi-api ./server
        - docker build -t tkavuri/multi-worker ./worker
        - docker build -t tkavuri/multi-nginx ./nginx

        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin


        - docker push tkavuri/multi-client
        - docker push tkavuri/multi-bginx
        - docker push tkavuri/multi-api
        - docker push tkavuri/multi-worker
